Full_name = input("Enter your full name:")
Age = int(input("Enter your age:"))
Student_ID = input("Enter your ID:")
City = input("Enter your city:")
University = input("Enter your university:")
Department = input("Enter your department:")
Email = input("Enter your email:")
Phone_number = input("Enter your phone number:")
Favorite_programming_language = input("Enter your favorite programming language:")
Programming_goal = input("Enter your programming goal:")


print("==========================================")
print("      AKIBA STUDENT PROFILE               ")
print("==========================================")
print(f"Name: {Full_name}")
print(f"Age: {Age}")    
print(f"Student ID: {Student_ID}")
print(f"City: {City}")
print(f"University: {University}")
print(f"Department: {Department}")
print(f"Email: {Email}")
print(f"Phone number: {Phone_number}")
print(f"Favorite programming language: {Favorite_programming_language}")
print()
print(f"Programming goal: {Programming_goal}")
print()
print("============================================")